Im4 java
FitchburgCS-Club/DiscordBot pull request #10
Opened 2020-12-24 01:48 UTC by zja203

Adds IM4Java, a Java image manipulation library, and adds a command for blurring images

2020-12-24 02:00 UTC, perplexedMurfy commented on src/main/java/com/fsucsc/discordbot/Command.java
> +	BLUR("blur", "[blurAmount]", "Blurs an attached image. You can optionally specify an amount for blurring. The command defaults to 2.0") {
Is there a max and a min that blurAmount can be? If so, document it.

2020-12-24 02:01 UTC, perplexedMurfy commented on src/main/java/com/fsucsc/discordbot/Command.java
> +	MBLUR("mblur", "[blurAmount] [blurAngle]", "Applies motion blur to an image. Defaults are 10.0 and 45.0") {
Similar thing as last time. Is there/What is the range of valid values for blurAmount and blurAngle? Add this to the help string.

2021-01-20 01:27 UTC, perplexedMurfy requested changes
Still getting used to this github reviewing thing. I think this is how I ask you to make changes via this platform?

2021-01-20 01:27 UTC, perplexedMurfy commented on src/main/java/com/fsucsc/discordbot/Command.java
> +							Bot.SendMessage(event.getChannel(), "An unexpected exception occurred! Here's the info:\n" + sw.toString());
Use Bot.ReportStackTrace() instead of the 3 lines you wrote

2021-01-20 01:27 UTC, perplexedMurfy commented on src/main/java/com/fsucsc/discordbot/Command.java
> +						Bot.SendMessage(event.getChannel(), "Failed to convert image Here's the info:\n" + sw.toString());
Same as above, Convert to Bot.ReportStackTrace()

2021-01-20 01:27 UTC, perplexedMurfy commented on src/main/java/com/fsucsc/discordbot/Command.java
> +					Bot.SendMessage(event.getChannel(), "Failed to download image Here's the info:\n" + sw.toString());
Convert to Bot.ReportStackTrace()

2021-01-20 01:27 UTC, perplexedMurfy commented on src/main/java/com/fsucsc/discordbot/Command.java
> +							Bot.SendMessage(event.getChannel(), "An unexpected exception occurred! Here's the info:\n" + sw.toString());
Convert to Bot.ReportStackTrace()

2021-01-20 01:27 UTC, perplexedMurfy commented on src/main/java/com/fsucsc/discordbot/Command.java
> +						Bot.SendMessage(event.getChannel(), "Failed to convert image Here's the info:\n" + sw.toString());
Convert to Bot.ReportStackTrace()

2021-01-20 01:27 UTC, perplexedMurfy commented on src/main/java/com/fsucsc/discordbot/Command.java
> +					Bot.SendMessage(event.getChannel(), "Failed to download image Here's the info:\n" + sw.toString());
Convert to Bot.ReportStackTrace()

2021-01-20 01:27 UTC, perplexedMurfy commented on src/main/java/com/fsucsc/discordbot/Command.java
> +                    Bot.SendMessage(event.getChannel(), "An unexpected exception occurred! Here's the info:\n" + sw.toString());
Convert to Bot.ReportStackTrace()

2021-01-20 01:27 UTC, perplexedMurfy commented on src/main/java/com/fsucsc/discordbot/Bot.java
> +
Fix Formatting

2021-01-20 01:48 UTC, zja203 reviewed
I ran the autoformatter and changed the stacktrace reporting to use the bot function

2021-01-20 03:06 UTC, perplexedMurfy approved these changes

2021-01-20 03:07 UTC, merged